### ISSUE TITLE
recherche développeuse/développeur Android  pour mission en prestation

### ISSUE THREAD

**Issue by ogrange** [lemonde/team#1]
# Recherche développeuse/développeur Android  pour mission en prestation

Vous voulez développer l’application de news sous Android la plus utilisée en France ? Vous voulez participer à l’invention de nouveaux modes de consommation de l’info en mobilité ? Vous êtes geek et technophile mais vous adorez jouer le jeu de la création collective ?

Ce poste vous intéressera.

## Société

La Société Editrice du Monde édite le quotidien Le Monde, son site internet www.lemonde.fr et ses applications mobiles et tablettes.

## Poste

Vous serez intégré(e) au pôle développement de la direction technique. Vous serez en charge du développement et de la maintenance de nos applications natives Android.

Outre le développement, vous participerez aux phases de conception.  Vous partagerez ainsi vos expériences des bonnes pratiques en expérience utilisateur et vos réflexions sur les nouveaux usages mobiles par le dialogue avec les différents interlocuteurs du projet (responsable fonctionnel, régie publicitaire, développeurs du site ou de l’appli iOS, management).

L'environnement technique est le suivant :
- Java / Kotlin
- Android studio
- webservices JSON 
- backend : PHP/Node.js/PostgreSQL/Oracle/Redis
- Jenkins
- Git

## Profil

Vous avez déjà réalisé plusieurs applications Android et souhaitez participer au déploiement de la marque Le Monde sur mobile.

Notre métier est l'information en ligne : nous recherchons donc une personne imprégnée de la culture Internet et partageant notre passion. Cette passion et votre curiosité technique vous poussent à effectuer une veille technique assidue (Twitter, RSS, Meetups, conférences...).

Vous parlez à l’oreille des usines de développements et des tests automatisés. KISS et DRY sont vos mantras. Les designs patterns mangent dans votre main (sans vous mordre).

Idéalement, vous possédez également une expérience du développement dans d'autres environnements mobiles (iOS, React Native) ou de webapps HTML/Javascript.

## Mission

La mission, en régie de 3 mois renouvelables, a lieu dans nos locaux au 80 boulevard Blanqui, dans le 13ème arrondissement de Paris.

La langue utilisée est le français.

Processus de recrutement :
- pré-entretien par téléphone
- entretien dans nos locaux lors desquels vous passerez un test technique
- dernier entretien général

Evaluations sur vos savoir-faire et vos savoir-être.

Réponse sous quelques jours.

## Contact

Vincent Pomageot - Lead Dev Mobile : pomageot@lemonde.fr

**Comment by vipom** [comment]
👐

**Comment by vipom** [comment]
🎉

**Comment by vipom** [comment]
👐

**Comment by vipom** [comment]
🐼
