### ISSUE TITLE
Recherche développeur·euse Android/React Native

### ISSUE THREAD

**Issue by vipom** [lemonde/team#14]
# Recherche développeur·euse Android/React Native

## Société

La Société Éditrice du Monde édite le quotidien Le Monde, son site internet www.lemonde.fr et ses applications mobiles et tablettes.

## Poste

Vous serez intégré·e au pôle développement de la direction technique. Vous serez en charge du développement et de la maintenance de nos applications natives Android.

Vous participerez aussi aux phases de conception : vous partagerez ainsi vos expériences des bonnes pratiques en expérience utilisateur et vos réflexions sur les nouveaux usages mobiles par le dialogue avec les différents interlocuteurs du projet (responsable fonctionnel, régie publicitaire, développeurs du site ou de l’appli iOS, management).

L'environnement technique est le suivant :
- Java / Kotlin / React Native
- Android studio
- webservices JSON 
- backend : PHP/Node.js/PostgreSQL/Oracle/Redis
- Jenkins
- Git

## Profil

Vous avez déjà réalisé plusieurs applications Android et souhaitez participer au déploiement de la marque Le Monde sur mobile.

Vous êtes passionné·e, curieux·se et effectuez une veille technologique assidue (Twitter, RSS, Meetups, conférences...).

Idéalement, vous possédez également une expérience en React Native.

## Mission

La mission, en régie de 3 mois renouvelables, a lieu dans nos locaux au 80 boulevard Blanqui, dans le 13ème arrondissement de Paris.

La langue utilisée est le français.

Processus de recrutement :
- pré-entretien par téléphone
- entretien dans nos locaux lors desquels vous passerez un test technique
- dernier entretien général

Evaluations sur vos savoir-faire et vos savoir-être.

Réponse sous quelques jours.

## Contact

Vincent Pomageot - Lead Dev Mobile : pomageot@lemonde.fr

**Comment by NicoO02** [comment]
Bonjour Vincent, 

J'espère que vous allez bien. 

Je me suis permis de vous faire parvenir les dossiers de compétences de deux développeurs Android disponible prochainement par mail. 

Merci par avance pour votre retour. 

Nicolas LEMEILLE - iD.apps 
06 43 35 17 34
