### ISSUE TITLE
Groupe Le Monde : Recherche développeuse/développeur Android sénior pour mission en prestation

### ISSUE THREAD

**Issue by SachaMorard** [lemonde/team#31]
## Société

La direction technique du groupe Le Monde est en charge du développement des sites internet et applications mobiles du Monde, de Télérama, du Huffington Post et de Courrier International.

## Poste

Vous serez intégré(e) au pôle mobile de la direction technique. Vous serez en charge du développement et de la maintenance de nos applications natives Android (5 applications).

Outre le développement, vous participerez aux phases de conception. Vous partagerez ainsi vos expériences des bonnes pratiques en expérience utilisateur et vos réflexions sur les nouveaux usages mobiles par le dialogue avec les différents interlocuteurs du projet (responsable fonctionnel, régie publicitaire, développeurs du back office ou de l'équipe iOS, management, etc.).

L'environnement technique est le suivant :
- Kotlin, Dagger2, LiveData/Flow, Coroutines, Compose, MVVM
- Utilisation de webviews
- Webservices JSON (backend en PHP)
- Jira, Git, Jenkins, Gradle

## Profil

Vous avez déjà réalisé plusieurs applications Android et souhaitez participer au déploiement des marques du groupe Le Monde sur mobile.

Vous maîtrisez parfaitement la plateforme Android (écosystème, frameworks, optimisations, bonnes pratiques…).

Vous êtes sensible à l'architecture et à la nécessité de respecter de bonnes pratiques de développement. Notamment vous êtes capable d'écrire du code clair, documenté et réutilisable.

Notre métier est l'information en ligne : nous recherchons donc une personne imprégnée de la culture Internet et partageant notre passion. Cette passion et votre curiosité technique vous poussent à effectuer quotidiennement une veille technique (Twitter, RSS, meetups, conférences...).

## Mission

La mission, en régie, a lieu dans nos locaux au 67 avenue Pierre Mendès-France, dans le 13ème arrondissement de Paris. Le télétravail est possible. La langue utilisée est le français.

Processus de recrutement :
- Pré-entretien par visioconférence
- Second entretien lors duquel vous devrez passer un test technique

Evaluation sur vos savoir faire et savoir être.

Note: Les ESN peuvent nous présenter des candidats. Il n'y a pas de nombre d'années d'expériences exigé, mais le niveau attendu est élevé. Il s'agit d'une mission longue, nous cherchons un candidat qui souhaite s'investir sur le long terme.

## Contacts

Merci de nous contacter par mail exclusivement.

Nicolas Viry – Tech Lead Android : viry@lemonde.fr
Guillaume Hugues – VP Engineering Mobile : hugues@lemonde.fr (en copie)

**Comment by NathanGouet** [comment]
Bonjour messieurs,
Comme envoyé dans mon mail pour Guillaume vendredi, je souhaite répondre à votre appel d'offre avec le profil de Nicolas.
 Nicolas a été diplômé en 2017 de l’EISTI et a travaillé dernièrement pour Sopra sur une mission chez Orange où il a travaillé en Agile en tant que dev Middleware Kotlin. Sa double compétence iOS/Android ainsi que ses capacités d’adaptation feront de lui une plus-value sur votre projet.

Je suis disponible par téléphone au 06 31 13 30 38

Bonne journée à vous
[DT Exomind Nicolas Dev Android : iOS.pdf](https://github.com/lemonde/team/files/4052640/DT.Exomind.Nicolas.Dev.Android.iOS.pdf)

**Comment by NathanGouet** [comment]
Bonne journée à vous et au plaisir d'échanger avec vous

**Comment by ghugues** [comment]
Le recrutement pour ce poste est en pause et reprendra à partir du 22 août 2022.
