### ISSUE TITLE
Recherche développeuse/développeur PHP pour mission en prestation

### ISSUE THREAD

**Issue by gomesfabrice** [lemonde/team#35]
# Recherche Développeur PHP confirmé en prestation

## Société

Le Groupe Le Monde produit et maintient des applications, telles que le site lemonde.fr, telerama.fr des applications mobiles et tablettes, et des applications backoffice.

## Poste

Vous serez intégré(e) au pôle développement de la direction technique, et plus précisément à l'équipe Web de Télérama. En collaboration avec d’autres développeurs et sous la direction du tech lead, vos missions seront les suivantes:

* Effectuer la maintenance applicative de nos applications back-end
* Développer des nouvelles fonctionnalités, leurs tests et faire de la revue de code.
* Participer à l’amélioration continue ainsi qu’à la continuité de service.

Vous serez amené à intervenir sur l’environnement technique suivant :

* Phalcon
* PostgreSQL 9.5
* Redis, Pub/Sub
* PHPUnit
* JavaScript, Webpack
* Google Cloud Platform
* Environnements de dev sous docker
* Gestion des sources sous git, github

## Profil

Vous justifiez d'une expérience de 2 à 5 ans dans le développement web.

## Compétences

Vous avez une expérience significative dans le développement PHP & JavaScript.
Vous maîtrisez les bonnes pratiques de conception, de qualité, de tests, d’intégration continue et de performance. HTTP n’a aucun secret pour vous. KISS et DRY sont vos mantra.
Nous recherchons une personne imprégnée de la culture Internet et partageant notre passion du web. Cette passion et votre curiosité technique vous poussent à effectuer une veille technique soutenue.
Une expérience sur des sites médias et/ou à fort traffic serait un plus.

En résumé :
* Bonne maîtrise de PHP
* Pratique courante des tests
* Curiosité technique
* Bonnes qualités relationnelles
* Alignement avec les valeurs du manifeste agile

## Mission

Démarrage de mission : ASAP
Durée : régie de 3 mois renouvelable
Budget : nous contacter

La mission a lieu dans les locaux de Télérama au 8 rue Jean Antoine de Baïf, dans le 13ème arrondissement de Paris.

La langue utilisée est le français.

Processus de recrutement :

- pré-entretien par téléphone
- entretien dans nos locaux lors desquels vous devrez présenter vos applications et passer un test technique
- dernier entretien général

Evaluations sur vos savoir faire et vos savoir être.

Réponse sous quelques jours.

## Contacts

Fabrice Gomes - presta-fgomes@vmmagazines.com
Ludovic Werwinski - werwinski@lemonde.fr

**Comment by clementinebeezen** [comment]
Bonjour, je souhaite vous proposer la candidature de notre collaborateur salarié Nizar disponible immédiatement. Nizar dispose de près de 5 ans d'expérience en environnement PHP. Je vous joins ici son CV ainsi que les tests techniques qu'il a pu réaliser sur la plateforme codingame.
[CodinGame - Développeur_PHP_Full_Stack_-_Intermédiaire - BARHOUMI_Nizar.pdf](https://github.com/lemonde/team/files/3779738/CodinGame.-.Developpeur_PHP_Full_Stack_-_Intermediaire.-.BARHOUMI_Nizar.pdf)
[CodinGame - Symfony - BARHOUMI.pdf](https://github.com/lemonde/team/files/3779739/CodinGame.-.Symfony.-.BARHOUMI.pdf)
[Dossier_de_compétences_NB_Beezen.pdf](https://github.com/lemonde/team/files/3779733/Dossier_de_competences_NB_Beezen.pdf)

A votre disposition pour en discuter

**Comment by Achraf-ConsultIT** [comment]
Bonjour,

Je me permets de partager avec vous les dossiers de compétences de nos consultant disponibles Asap,

Jasser : Disponible 18/07 
Ayoub : Disponible 18/07 

Je reste en attente de votre retour

aj@consult-it.com
01 89 16 40 66

cdlt 
[Dossier COMPETENCES -SDI.docx](https://github.com/lemonde/team/files/9091992/Dossier.COMPETENCES.-SDI.docx)
[Dossier COMPETENCES-ABU.docx](https://github.com/lemonde/team/files/9091994/Dossier.COMPETENCES-ABU.docx)

**Comment by clementinebeezen** [comment]
Bonjour
Quel est le TJM d’Ayoub?

Envoyé de mon iPhone
