### ISSUE TITLE
Développeu(r|se) PHP confirmé(e) en prestation

### ISSUE THREAD

**Issue by takman1** [lemonde/team#64]
# Recherche Développeur(euse) PHP confirmé(e) en prestation

## Société

Le Groupe Le Monde produit et maintient des applications, telles que le site lemonde.fr, telerama.fr des applications mobiles et tablettes, et des applications backoffice.

## Poste

Vous serez intégré(e) au pôle développement de la direction technique, et plus précisément à l'équipe "Télérama" du Monde. En collaboration avec d’autres développeurs et sous la direction du Tech lead et des VP Engineers, vos missions seront les suivantes:

* Développer de nouvelles fonctionnalités, leurs tests et faire de la revue de code.
* Effectuer la maintenance de l'existant
* Participer à l’amélioration continue ainsi qu’à la continuité de service.

Vous serez amené(e) à intervenir sur l’environnement technique suivant :

* Phalcon
* PostgreSQL
* Redis, Pub/Sub
* PHPUnit
* JavaScript, Webpack
* Google Cloud Platform
* Docker/Docker-compose/K8S
* Git, GitHub
* Travis

## Profil

Vous justifiez d'une expérience de plusieurs années dans le développement web.

## Compétences

Vous avez une expérience significative dans le développement backend en PHP7 et front en JavaScript/CSS.
Vous maîtrisez les bonnes pratiques de conception, de qualité, de tests, d’intégration continue et de performance.
Vous connaissez bien le protocole HTTP ainsi les principes/best practices KISS, SOLID et DRY.
Vous êtes curieux et passionné du web et vous aimez/voulez partager cette passion.
Une expérience sur des sites médias et/ou à fort traffic serait un plus.

En résumé :
* Bonne maîtrise de PHP7
* Connaissance et application de design pattern
* Pratique courante des tests
* Curiosité technique
* Bonnes qualités relationnelles
* Alignement avec les valeurs du manifeste agile

## Mission

Démarrage de mission : ASAP
Durée : régie (remote partiel) de 3-6 mois renouvelable
Budget : nous contacter

La mission a lieu dans les locaux du Monde au 67 avenue Pierre Mendès-France Paris.

La langue utilisée est le français.

Processus de recrutement :

- entretien par visioconférence avec tests techniques
- dernier entretien général avec la direction

Evaluations sur votre savoir faire et votre savoir être.

Réponse sous quelques jours.

## Contacts

Talbi - presta-mtalbi@vmmagazines.com

**Comment by Achraf-ConsultIT** [comment]
Bonjour,

Je me permets de partager avec vous les dossiers de compétences de nos consultant disponibles Asap,

Jasser : Disponible 18/07
Ayoub : Disponible 18/07

Je reste en attente de votre retour

[aj@consult-it.com](mailto:aj@consult-it.com)
01 89 16 40 66

cdlt
[Dossier COMPETENCES -SDI.docx](https://github.com/lemonde/team/files/9091992/Dossier.COMPETENCES.-SDI.docx)
[Dossier COMPETENCES-ABU.docx](https://github.com/lemonde/team/files/9091994/Dossier.COMPETENCES-ABU.docx)
