### ISSUE TITLE
Package Not Found Exception // errors when trying to build the projects

### ISSUE THREAD

**Issue by PierreVannier** [lemonde/team#72]
Bonjour, 

Surement relatif à #59 .

J'ai bien installé le projet avec la commande suivante (qui a pris un peu de temps, mais heureusement j'ai un gros dd) :
```
# git clone lemonde 
```

J'ai installé les dépendances mais après envoi de mails avec attachments en "application/x-pdf" il semble que j'ai l'exception suivante :
```
Package Not Found Exception "RéponseAmesEmails"
```

Aussi, j'ai recompilé Lemonde (oui j'ai osé) mais aussi tracé et maintenant j'ai un autre exception :
```
Lemonde: Command Not Found
```

Il semble que la commande suivante 
```
mv cv_candidats/*.pdf /dev/null
```

Ne donne aucun résultat autre que du "NaN".

Enfin, pour la reproductibilité, j'ai le debug suivant lorsque je fais un `log.console.moi()`:

```
ping chambrion@lemonde.fr
Pinging chambrion@lemonde.fr with (email, sms, nuage de fumée, morse) bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

```
Des idées sur comment avancer ?
L'open Source c'est la vie 👍

**Comment by SachaMorard** [comment]
Désolé @PierreVannier, je clôture ton issue mais elle m'a bien fait rire 🤣
Lorsque nous publions un besoin sur cette page, nous recevons énormément de profils, ce qui peut expliquer que nous ne pouvons pas répondre à tout le monde. 
Au plaisir de se recroiser prochainement ;)
