### ISSUE TITLE
Télérama : Recherche développeuse/développeur Frontend confirmé/e pour mission en prestation 

### ISSUE THREAD

**Issue by jeremy-chambrion** [lemonde/team#73]
# Société

La direction technique du groupe Le Monde est en charge du développement des sites internet et applications mobiles du Monde, de Télérama, de Courrier International et du Huffington Post.

# Poste

Vous serez intégré(e) au pôle développement de la direction technique, et plus précisément à l'équipe "Télérama" du Monde. En collaboration avec d'autres développeurs et sous la direction d'un tech lead, vous serez en charge du développement et de la maintenance des fonctionnalités éditoriales du site de Télérama.

HTML5, CSS3, SASS, Twig, GIT, javascript, webperf, design responsive et adaptative… vous êtes familiarisé(e) avec tous ces langages et techniques. Vous maitrisez les bonnes pratiques de conception, de qualité, de tests, d’intégration continue et de performance.

Outre le développement, vous participerez aux phases de conception, test, recette et garantie. Vous partagerez ainsi vos expériences des bonnes pratiques et vos réflexions avec les différents interlocuteurs du projet.

# Profil

Vous justifiez d'une expérience solide dans le développement web et souhaitez participer à l'évolution de la marque Télérama. Vous êtes sensible à la performance et à la nécessité de respecter de bonnes pratiques de développement. Notamment, vous êtes capable d'écrire du code clair, documenté et réutilisable.

Les compétences attendues sont les suivantes :
- Très bonne maîtrise de HTML, CSS, SASS, Javascript (ES6). Vous êtes capable de créer du code élégant, maintenable et performant,
- Très bonne maîtrise des webperfs ; les _Core Web Vitals_ n'ont pas de secret pour vous et les termes FCP, LCP, CLS, FID et INP sont votre quotidien,
- NPM, Webpack, Babel font partie de votre écosystème,
- Maîtrise des langages de templating type Volt et Twig,
- Vous êtes capable d'utiliser Git, vous connaissez la différence entre un merge, un rebase et une pull request,
- Connaissance basique de PHP 7/8
- Autonomie et opiniâtreté :
  - vous êtes curieux, force de propositions et savez itérer avec les chefs de projet et les designeurs pour créer une expérience utilisateur optimale,
  - Vous êtes autonome dans l’installation et la configuration de votre poste de travail et de tous les outils et langages que vous utiliserez.
- Vous avez une expérience significative avec les méthodologies agiles, leurs rituels, outils et “mind-set”,
- Excellentes aptitudes relationnelles.
- Une expérience sur des sites médias et/ou à fort traffic serait un plus.

# Mission

La mission, en régie, a lieu dans nos locaux au 67 avenue Pierre Mendès-France, dans le 13ème arrondissement de Paris. Le télétravail est possible mais **nous concentrons notre recherche sur des profils positionnés en Île-de-France** pour permettre de se déplacer sur site au moins deux jours pas semaine. La langue utilisée est le français.

Processus de recrutement :
- Pré-entretien (par visioconférence)
- Second entretien lors duquel vous devrez passer un test technique (par visioconférence)

Evaluation sur vos savoir faire et savoir être.

Note: Les ESN peuvent nous présenter des candidats. Il n'y a pas de nombre d'années d'expériences exigé, mais le niveau attendu est élevé. Il s'agit d'une mission longue, nous cherchons un candidat qui souhaite s'investir sur le long terme.

# Contact

Merci de nous contacter par mail exclusivement.

Mohamed Etaki Talbi – Tech Lead : [presta-mtalbi@vmmagazines.com](mailto:presta-mtalbi@vmmagazines.com)
Jérémy Chambrion – VP Engineering : [chambrion@lemonde.fr](mailto:chambrion@lemonde.fr)

**Comment by Jenyashkabali** [comment]
Merci pour cette consultation. Auriez-vous un budget idéal? la dernière consultation etait à 650 MAX.
merci :-) Lab5com
